# Fixed Fly.io Configuration for Skillyme MySQL Database
app = "skillyme-mysql"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.mysql"

[env]
  MYSQL_ROOT_PASSWORD = "ponsomu756@"
  MYSQL_DATABASE = "skillyme_app"
  MYSQL_USER = "skillyme_root"
  MYSQL_PASSWORD = "ponsomu756@"

[[services]]
  protocol = "tcp"
  internal_port = 3306

  [[services.ports]]
    port = 3306
    handlers = ["tcp"]
    force_https = false

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "30s"

[mounts]
  source = "skillyme_data"
  destination = "/var/lib/mysql"
