services:
  - type: web
    name: skillyme-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/test

databases:
  - name: skillyme-database
    plan: starter
    databaseName: skillyme_production
    user: skillyme_user
